//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Savonia.Measurements.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessKey
    {
        public AccessKey()
        {
            this.Queries = new HashSet<Query>();
        }
    
        public int ProviderID { get; set; }
        public string Key { get; set; }
        public int AccessControl { get; set; }
        public Nullable<System.DateTimeOffset> ValidFrom { get; set; }
        public Nullable<System.DateTimeOffset> ValidTo { get; set; }
        public Nullable<short> KeyId { get; set; }
        public string KeyEncrypt { get; set; }
        public string Info { get; set; }
    
        public virtual Provider Provider { get; set; }
        public virtual ICollection<Query> Queries { get; set; }
    }
}
