//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Savonia.Measurements.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meta
    {
        public string Context { get; set; }
        public string Object { get; set; }
        public string Tag { get; set; }
        public int Version { get; set; }
        public byte[] Data { get; set; }
    }
}
