//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Savonia.Measurements.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider
    {
        public Provider()
        {
            this.AccessKeys = new HashSet<AccessKey>();
            this.Measurements = new HashSet<Measurement>();
            this.Sensors = new HashSet<Sensor>();
        }
    
        public int ID { get; set; }
        public string Key { get; set; }
        public string Info { get; set; }
        public string Name { get; set; }
        public string Owner { get; set; }
        public bool IsPublicDomain { get; set; }
        public System.DateTime Created { get; set; }
        public string Tag { get; set; }
        public System.Data.Entity.Spatial.DbGeography Location { get; set; }
        public string ContactEmail { get; set; }
        public Nullable<System.DateTime> ActiveFrom { get; set; }
        public Nullable<System.DateTime> ActiveTo { get; set; }
        public Nullable<System.DateTime> DataStorageUntil { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual ICollection<AccessKey> AccessKeys { get; set; }
        public virtual ICollection<Measurement> Measurements { get; set; }
        public virtual ICollection<Sensor> Sensors { get; set; }
    }
}
