//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Savonia.Measurements.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Query
    {
        public int ID { get; set; }
        public int ProviderID { get; set; }
        public string Key { get; set; }
        public string Object { get; set; }
        public string Tag { get; set; }
        public Nullable<int> Take { get; set; }
        public Nullable<System.DateTimeOffset> From { get; set; }
        public Nullable<System.DateTimeOffset> To { get; set; }
        public string Sensors { get; set; }
        public string Name { get; set; }
    
        public virtual AccessKey AccessKey { get; set; }
    }
}
