//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Savonia.Measurements.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sensor
    {
        public int ProviderID { get; set; }
        public string Tag { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Rounding { get; set; }
        public string Unit { get; set; }
        public string Context { get; set; }
        public System.Data.Entity.Spatial.DbGeography Location { get; set; }
    
        public virtual Provider Provider { get; set; }
    }
}
